/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package yetris.view;
import java.awt.Dimension;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;   
import yetris.model.Model;

public class SidePaneView extends javax.swing.JPanel {

    Model model;
    NextTetriminoView nextTetriminoView;

    ImageIcon iconRestart, iconPlay;
    /**
     * Creates new form SidePaneView
     */
    public SidePaneView(Model model) {
        initComponents();
        this.model = model;

        nextTetriminoView = new NextTetriminoView(model);
        panelNext.setLayout(new FlowLayout());
        panelNext.setAlignmentX(Component.CENTER_ALIGNMENT);
        panelNext.setAlignmentY(Component.CENTER_ALIGNMENT);
        panelNext.add(nextTetriminoView);
        panelNext.setVisible(model.getConfig().showNextTetrimino);

        iconRestart = new ImageIcon(this.getClass().getResource("/img/restart.png"));
        iconPlay = new ImageIcon(this.getClass().getResource("/img/play.png"));
        btnRestart.setFocusable(false);
        btnRestart.setIcon(iconPlay);
    }

    public void refresh(){
        nextTetriminoView.refresh();
    	labelScore.setText(Integer.toString(model.getScore()));
    	labelLevel.setText(Integer.toString(model.getLevel()));
    	labelLines.setText(Integer.toString(model.getLines()));
    }

    public void initStartGame(){
        btnRestart.setText("Restart");
        btnRestart.setIcon(iconRestart);
    }

	public void addActionListener(ActionListener al){
		btnRestart.addActionListener(al);
	}

    // @Override
    // public Dimension getPreferredSize(){
    //   return new Dimension(137, 350); // Should ideally never reach here
    // }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        labelScore = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelLevel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelLines = new javax.swing.JLabel();
        panelNext = new javax.swing.JPanel();
        btnRestart = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 5, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Score:");
        jPanel1.add(jLabel5);

        labelScore.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelScore.setForeground(new java.awt.Color(51, 153, 0));
        labelScore.setText("100");
        labelScore.setName("labelScore"); // NOI18N
        jPanel1.add(labelScore);
        labelScore.getAccessibleContext().setAccessibleDescription("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Level:");
        jPanel1.add(jLabel8);

        labelLevel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLevel.setText("100");
        jPanel1.add(labelLevel);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Lines:");
        jPanel1.add(jLabel10);

        labelLines.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLines.setText("100");
        jPanel1.add(labelLines);

        panelNext.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Next", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        panelNext.setLayout(null);

        btnRestart.setText("Start");
        btnRestart.setActionCommand("restart");
        btnRestart.setBorder(null);
        btnRestart.setFocusable(false);
        btnRestart.setMinimumSize(new java.awt.Dimension(90, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelNext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelNext, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>                                          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRestart;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLevel;
    private javax.swing.JLabel labelLines;
    private javax.swing.JLabel labelScore;
    private javax.swing.JPanel panelNext;
    // End of variables declaration//GEN-END:variables

}
